- id:                   1
  code:                 usd
  symbol:               '$'
  type:                 fiat
  precision:            2
  base_factor:          1
  visible:              true
  quick_withdraw_limit: 1000

- id:                   2
  code:                 dash
  symbol:               'Đ'
  type:                 coin
  precision:            8
  base_factor:          100_000_000
  visible:              true
  quick_withdraw_limit: 2
  options:
    #
    # API client configuration.
    api_client: DASH
    #
    # Dashd specific configuration.
    json_rpc_endpoint: http://peatio:s3WfKUPkSNpY9p5C@35.204.178.66:9998
    #
    # BitGo specific configuration.
    bitgo_test_net:              on
    bitgo_wallet_id:             ~
    bitgo_wallet_address:        ~
    bitgo_wallet_passphrase:     ~
    bitgo_rest_api_root:         https://test.bitgo.com/api/v2
    bitgo_rest_api_access_token: ~
    #
    # Block explorer configuration.
    wallet_url_template:      https://live.blockcypher.com/dash/address/#{address}
    transaction_url_template: https://live.blockcypher.com/dash/tx/#{txid}

- id:                   3
  code:                 eth
  symbol:               'Ξ'
  type:                 coin
  precision:            8
  base_factor:          1_000_000_000_000_000_000
  visible:              true
  quick_withdraw_limit: 2
  options:
    #
    # API client configuration.
    api_client: ETH
    #
    # Ethereum node specific configuration.
    json_rpc_endpoint: http://35.204.10.145:8545
    #
    # BitGo specific configuration.
    bitgo_test_net:              on
    bitgo_wallet_id:             ~
    bitgo_wallet_address:        ~
    bitgo_wallet_passphrase:     ~
    bitgo_rest_api_root:         https://test.bitgo.com/api/v2
    bitgo_rest_api_access_token: ~
    #
    # Block explorer configuration.
    wallet_url_template:      https://etherscan.io/address/#{address}
    transaction_url_template: https://etherscan.io/tx/#{txid}
