- id:            dashusd
  ask_unit:      dash
  bid_unit:      usd
  ask_fee:       0.0015
  bid_fee:       0.0015
  ask_precision: 4
  bid_precision: 4
  position:      100
  visible:       true

- id:            ethusd
  ask_unit:      eth
  bid_unit:      usd
  ask_fee:       0.0015
  bid_fee:       0.0015
  ask_precision: 4
  bid_precision: 4
  position:      102
  visible:       true

- id:            ethdash
  ask_unit:      eth
  bid_unit:      dash
  ask_fee:       0.0015
  bid_fee:       0.0015
  ask_precision: 4
  bid_precision: 4
  position:      103
  visible:       true
