- id: 200
  currency: usd
  fixed: 2
  fee_max: 0
  min: 100
  max: 50000
  fee: 0.003
  proportion: true
  inuse: true

- id: 400
  currency: dash
  fixed: 8
  fee: 0.0005
  inuse: true

- id: 600
  currency: eth
  fixed: 8
  fee: 0.0005
  inuse: true

